### ISSUE TITLE
Bottom left buttons, in each post, overlap

### ISSUE THREAD

**Issue by ErikThorsell** [SimonAlling/better-sweclockers#171]
Version: 2020.11.12.20.17.39
Browser: Firefox 82.0.3 (64-bit) on Windows

![bild](https://user-images.githubusercontent.com/5284470/99036009-23689f00-2581-11eb-9020-1cedb3dcb656.png)

**Comment by Soitora** [comment]
@SimonAlling, SweClockers use `.is-disabled` as a class on the `.button` (because they're `a` or `span` instead of a `button`).

It would be nice to follow their standards but on the other hand using a `button` with the `disabled` attribute is more preferred so I'll push an update to accomodate the disable attribute as well.
